name: Build & Tests
on: [push, pull_request]
env:
  SUBSTRATE_NODE_VERSION: 'v0.9.40' 
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Download Substrate Node
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'substrate-developer-hub/substrate-node-template'
          version: 'tags/${{ env.SUBSTRATE_NODE_VERSION }}'
          file: 'node-template-x86_64-apple-darwin.tar.gz'
      - name: Unpack Substrate Node
        run: tar -xvzf *.tar.gz
      - name: Build and Test SPM
        run: ./run_with_node.sh './node-template' 'swift test' 'swift_test_node_log.txt'
      - name: Upload node log
        uses: actions/upload-artifact@v3
        with:
          name: swift_test_node_log.txt
          path: swift_test_node_log.txt
      # - name: Update Cocoa Pods repo
      #   run: pod repo update
      # - name: Build and Test CocoaPods
      #   run: ./run_with_node.sh './node-template' 'pod lib lint --allow-warnings --fail-fast' 'pod_lint_node_log.txt'
      # - name: Upload node log
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pod_lint_node_log.txt
      #     path: pod_lint_node_log.txt
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.8.1
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Substrate Node
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'substrate-developer-hub/substrate-node-template'
          version: 'tags/${{ env.SUBSTRATE_NODE_VERSION }}'
          file: 'node-template-x86_64-unknown-linux-gnu.tar.gz '
      - name: Unpack Substrate Node
        run: tar -xvzf *.tar.gz
      - name: Build and Test
        run: ./run_with_node.sh './node-template' 'swift test' 'linux_swift_test_node_log.txt'
      - name: Upload node log
        uses: actions/upload-artifact@v3
        with:
          name: linux_swift_test_node_log.txt
          path: linux_swift_test_node_log.txt
