name: Publish CocoaPods package
on:
  release:
    types: [created]
env:
  SUBSTRATE_NODE_VERSION: 'v0.9.40' 
jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Download Substrate Node
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'substrate-developer-hub/substrate-node-template'
          version: 'tags/${{ env.SUBSTRATE_NODE_VERSION }}'
          file: 'node-template-x86_64-apple-darwin.tar.gz'
      - name: Unpack Substrate Node
        run: tar -xvzf *.tar.gz
      - name: Publish Pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          sed -i '' "s|[[:blank:]]*s\.version[[:blank:]].*|s.version = '${VERSION}'|g" Substrate.podspec
          ./run_with_node.sh './node-template' 'pod trunk push --allow-warnings' 'pod_push_node_log.txt'
      - name: Upload node log
        uses: actions/upload-artifact@v3
        with:
          name: pod_push_node_log.txt
          path: pod_push_node_log.txt
